obstacle_range: 6.0
raytrace_range: 8.5
footprint: [[0.12, 0.14], [0.12, -0.14], [-0.12, -0.14], [-0.12, 0.14]]
map_topic: /map
subscribe_to_updates: true
global_frame: map
robot_base_frame: base_footprint
always_send_full_costmap: true
static_layer:
    map_topic: /map
    subscribe_to_updates: true
plugins:
    - {name: inflation_layer,        type: "costmap_2d::InflationLayer"}
    - {name: obstacle_layer,         type: "costmap_2d::ObstacleLayer"}
obstacle_layer:
    observation_sources: depth
    laser_scan_sensor: {sensor_frame: base_footprint, data_type: LaserScan, topic: scan, marking: true, clearing: true, min_obstacle_height: 0.5, max_obstacle_height: 1.5, obstacle_range: 6.0, raytrace_range: 8.5}
    depth: {data_type: PointCloud2,topic: /zed2/point_cloud/cloud_registered,marking: true, clearing: true,min_obstacle_height: 0.7,max_obstacle_height: 3}
